services:
    flask:
        build:
            context: .
            dockerfile: Dockerfile
        image: ghetto-gex-live
        env_file: .env
        environment:
            SHARED_DIR: /shared
        volumes:
            - ${PWD}:/opt/app
            - shared:/shared
        restart: always
        ports:
          - 80:80
        working_dir: /opt/app
        command: python app.py 80
        healthcheck:
            test: curl -f http://localhost:80/ping || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
volumes:
    shared: