services:
    flask:
        volumes:
            - shared_sanbox:/shared
            - ${PWD}:/opt/app
    background:
        volumes:
            - shared_sanbox:/shared
volumes:
    shared_sanbox: